name: Trigger and types--v1

on:
  push:
    paths:
      - 'src/**'
      - 'my_test.txt'

jobs:
  branch:
    name: Testing Branch
    runs-on: ubuntu-latest

    steps:
      - name: My Branch
        run: echo "Trigger Testing"
        
