name: Trigger and types
on: 
 push:
  paths:
    - 'src/**'
    - 'my_test.txt'
    
jobs:
  Branch:
    name: Testing Branch
    runs-on: ubuntu-latest
    steps:
      - name: My Branch
        run: echo 'Trigger Testing'
        
  
  
